stages:
  - release

publish:
  stage: release
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - echo $NPM_TOKEN
    - echo $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - npm profile get
    - echo so cool
  #  - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"
  when: manual
    